---
- name: Create ec2 instances
  hosts: localhost
  tasks:
    - name: Create R1soft agent
      ec2:
        key_name: ansible
        instance_type: t2.micro
        assign_public_ip: yes
        region: eu-west-1
        image: ami-02a39bdb8e8ee056a
        vpc_subnet_id: subnet-060c7f4e
        group: allinall
        count: 1
...